### ISSUE TITLE
I am using Legend Chat

### ISSUE THREAD

**Issue by DevinderFTW** [marcelo-mason/SimpleClans#347]
Hello there i am using Legend Chat and before i use other chat plugin the SimpleClans was added automaticaly to the plugin essentials chat
but now the SimpleClans is not working its prefix for the LegendChat it need to call the prefix and i can't find which one it is like
{SimpleClan} 

better exemple
Also, i am using SimpleClans and while before I use LegendChat i don't get the Prefix of my clan when i talk.

Before using Legend Chat, i was using Essentials Chat:

The way i talk, [ForTheWin] [Owner]DevinderFTW: Hello guys
( [ForTheWin] > Is my Clan. [Owner] > GroupManager Rank. DevinderFTW > My Name )

Using the Legend Chat: [L] [Owner]DevinderFTW: Hello guys
( [L] Stands for LOCAL, [G] For Global )
Now I or either my players can't see their clan or what clan they belong to.

I am tring to figure it which bracket name, is to call the Clan Prefix like {SimpleClanPrefix} / {SClan} / {ClanPrefix}
Can't find the caller for the Prefix to be showing when talking

**Comment by marcelo-mason** [comment]
Try turning off `chat-compatibility-mode: true` in settings.

**Comment by DevinderFTW** [comment]
just give me the calling option so i can place on the plugin please?
Is it possible please?

**Comment by marcelo-mason** [comment]
You can't turn that off in-game.  You have to edit the config.yml.  Change:\

`chat-compatibility-mode: false` to `chat-compatibility-mode: true`

**Comment by DevinderFTW** [comment]
Doesn't have that in the LegendChat Plugin in the Config file

**Comment by DevinderFTW** [comment]
Could you please just give me the prefix to call the clan name? it would be or like something like this {SimpleClansPrefix}

**Comment by marcelo-mason** [comment]
Oh that is in the `plugins\SimpleClans\config.yml` file.

**Comment by marcelo-mason** [comment]
I have not added direct LegendChat compatibility.  No idea if any prefix is gonna work.  Try `clan`

**Comment by DevinderFTW** [comment]
my config file is empty, and inside the plugin's folder its Settings.yml
i already tried many but not working nothing

**Comment by DevinderFTW** [comment]
Send me you config file so i can just copy / paste into mine's

**Comment by marcelo-mason** [comment]
It should create one if one is not there.  In any case here is the default config:

```yaml
safe-civilians: false
tag:
    default-color: '8'
    max-length: 5
    bracket:
        color: '8'
        leader-color: '4'
        left: ''
        right: ''
    min-length: 2
    separator:
        color: '8'
        leader-color: '4'
        char: ' .'
settings:
    disable-messages: false
    tameable-mobs-sharing: false
    teleport-blocks: false
    teleport-home-on-spawn: false
    drop-items-on-clan-home: false
    keep-items-on-clan-home: false
    item-list: []
    show-debug-info: false
    mchat-integration: true
    enable-auto-groups: false
    chat-compatibility-mode: true
    rival-limit-percent: 50
    use-colorcode-from-prefix-for-name: true
    display-chat-tags: true
    unrivable-clans:
    - admin
    - staff
    - mod
    show-unverified-on-list: false
    blacklisted-worlds: []
    banned-players: []
    disallowed-tags:
    - vip
    - clan
    language: en
    disallowed-tag-colors:
    - '4'
    server-name: '&4SimpleClans'
    new-clan-verification-required: true
    allow-regroup-command: true
spout:
    in-game-tags: true
    alert-url: ''
    default-cape-url: http://i.imgur.com/pjqV6.png
    enable-clan-capes: true
    in-game-tags-colored: false
commands:
    more: more
    ally: ally
    clan: clan
    accept: accept
    deny: deny
    global: global
    force-priority: true
economy:
    creation-price: 100.0
    purchase-clan-create: false
    verification-price: 1000.0
    purchase-clan-verify: false
    invite-price: 20.0
    purchase-clan-invite: false
    home-teleport-price: 5.0
    purchase-home-teleport: false
    home-teleport-set-price: 5.0
    purchase-home-teleport-set: false
    money-per-kill: false
    money-per-kill-kdr-multipier: 10
kill-weights:
    rival: 2.0
    civilian: 0.0
    neutral: 1.0
clan:
    homebase-teleport-wait-secs: 10
    homebase-can-be-set-only-once: true
    min-size-to-set-rival: 3
    max-length: 25
    confirmation-for-promote: false
    trust-members-by-default: false
    confirmation-for-demote: false
    ff-on-by-default: false
    min-length: 2
    min-size-to-set-ally: 3
page:
    untrusted-color: '8'
    clan-name-color: b
    subtitle-color: '7'
    headings-color: '8'
    trusted-color: f
    leader-color: '4'
    separator: '-'
    size: 100
clanchat:
    rank.color: e
    tag-based-clan-chat: false
    name-color: e
    player-bracket:
        left: '<'
        right: '>'
    announcement-color: e
    message-color: b
    tag-bracket:
        color: e
        left: '['
        right: ']'
    enable: true
request:
    message-color: b
    ask-frequency-secs: 60
    max-asks-per-request: 1440
bb:
    color: e
    accent-color: '8'
    show-on-login: true
    size: 6
allychat:
    tag-color: b
    name-color: f
    player-bracket:
        left: <
        right: '>'
    message-color: '3'
    tag-bracket:
        color: '8'
        left: '['
        right: ']'
    enable: true
purge:
    inactive-player-data-days: 30
    inactive-clan-days: 7
    unverified-clan-days: 2
mysql:
    username: ''
    host: localhost
    enable: false
    password: ''
    database: ''
permissions:
  auto-group-groupname: true
  YourClanNameHere:
  - test.permission
performance:
  use-threads: false
  use-bungeecord: false
```
