### ISSUE TITLE
How to change the /clan command without an alias?

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#389]
How can I change the /clan command to /crew without having to hack it using an alias in commands.yml? This looks like it should be part of the config natively.

**Comment by erik1988** [comment]
I think you can do this in the config, look for this section;
```
commands:
  more: more
  ally: ally
  clan: clan
  accept: accept
  deny: deny
  global: global
  force-priority: true
```
change to;
  clan: crew

I have not tested this but I assume this would work.
