### ISSUE TITLE
Request: Supporting GriefPrevention

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#390]
Can you please support GriefPrevention, to trust/untrust/accesstrust your entire clan to a claim.
it would literally just need to send the list of people in your clan to GriefPrevention with the corresponding parameter.

**Comment by erik1988** [comment]
GP support giving trust to permissions groups, and simpleclans gives every clan member a permission. Therefore you can use "/trust clan.TAG", tag being the tag of the clan you want to give trust. Then everyone in that clan will have trust.

**Comment by FrozenBeard** [comment]
Interesting, this would make it very easy to implement into SimpleClans then!

**Comment by erik1988** [comment]
I dont know if you understood me, this already work. I use it on my server. 
If you check the permissions of a clan member you will see that he has a permission called clan.TAG.

So if your clan tag is called "RED", then you type "/trust clan.red", then everyone in that clan named red will have trust in that claim.

**Comment by FrozenBeard** [comment]
I fully understand the technically, what **you** are not understanding is this is not straight forward for players, this is not intuitive. I do not call my "clans" clans, mine are called crews, using the word "crew" does not make sence at all on my server. Since its already supported, it would be very simple to have an INTUITIVE EASY TO UNDERSTAND method for PLAYERS to trust their crews. players should not have to understand how permission nodes work, the whole reason griefprevetion works is that its incredibly simple, start trying to explain using permission nodes makes it complex, as I have already said, please read the message I already wrote; It would be very easy to implement a PROPER use of this already working feature, one that does not require a player to understand permission nodes, one that does not require a user to use a word that has nothing to do with the server "clan". we do not use that word.

**Comment by erik1988** [comment]
Alright, 
So your problem is pretty much that you want to change clan to crew. The "/trust clan/crew.TAG" works really well and make sense for players that know GP. I know because I use this on my own server. People can for instance give trust to allied clans as long as they know the TAG.

Now back to the crew vs clan thing:
If you have any experience with programming I suppose you can make a fork and then search for ("clan.") (including the """) in this https://github.com/marcelo-mason/SimpleClans/blob/0f561ed0f265853dc7822adc80d859c6f5b89709/src/main/java/net/sacredlabyrinth/phaed/simpleclans/managers/PermissionsManager.java

It should look something like this:
permission.playerAddGroup(cp.toPlayer(), "clan." + cp.getTag());

and ether replace it with crew, or make a variable that get its information from wherever you replaced clan with crew.

**Comment by erik1988** [comment]
btw I think the function for getting the clan alias registered in the config is something like this;
`getSettingsManager().getCommandClan()`

If you or someone else make a fork that support this function then maybe the author would consider adding it to the project.

**Comment by FrozenBeard** [comment]
Fantastic, thank you very much. my Java is terrible but I will pas this message on to a developer that knows what they are doing. The way I was thinking of seeing if I could do it with an alias in commands.yml probily no possible.

**Comment by RoinujNosde** [comment]
Solution that does not involve forking:

    @EventHandler
    public void onCommand(PlayerCommandPreprocessEvent event) {
        if (event.getMessage().startsWith("/trust crew.")) {
            event.setMessage(event.getMessage().replace("crew", "clan"));
        }
    }

**Comment by FrozenBeard** [comment]
Is there no way to do this with just the crew/clan name? as opposed to players having to use a permission? 
Im not sure what I would be using that code snippet for? seems like its just replacing /trust crew with trust clan? Im sure I could do that in chatcontrol wtih regex.
Could we not just get GriefPrevention support? 
If not maybe I can just somehow prefix the clan. using regex in chatcontrol.

**Comment by FrozenBeard** [comment]
Update, I just tried this with some players they did /trust clan.apple, the crew tag is apple. it did not work, but it displays that its trusted in GP by putting it in brackets. 
I checked my config.yml and apple is listed under the permissions section 

```
permissions:
  auto-group-groupname: false
  YourClanNameHere:
  - test.permission
  pr: []
  tdr: []
  poop: []
  tee: []
  cubi: []
  exi: []
  fire: []
  bros: []
  beer: []
  nova: []
  theh: []
  '14': []
  bbb: []
  chaos: []
  ae: []
  plyn: []
  night: []
  tiger: []
  pack: []
  ao: []
  ap: []
  seas: []
  rd: []
  solis: []
  grog: []
  re: []
  rf: []
  cove: []
  dawn: []
  orgn: []
  wind: []
  dean: []
  frej: []
  bd: []
  be: []
  bucks: []
  endkt: []
  nkc: []
  bl: []
  dead: []
  twp: []
  arson: []
  pent: []
  sd: []
  seb: []
  se: []
  sh: []
  silv: []
  gnd: []
  ire: []
  raids: []
  sp: []
  cb: []
  elves: []
  cc: []
  ce: []
  wolf: []
  cl: []
  union: []
  blood: []
  tc: []
  utror: []
  tg: []
  tm: []
  eka: []
  river: []
  god: []
  '42': []
  tr: []
  dc: []
  ts: []
  13c: []
  ace: []
  df: []
  kobo: []
  sum41: []
  tpbay: []
  ice: []
  apple: []
```
