### ISSUE TITLE
Request: Showing [clanname] in /a alias chat.

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#397]
Ally chat currently just says [ally] when they chat in /a, an option to customize this message along with displaying their clan name in the config would be much appreciated, [ally] seems to be hard coded in!

**Comment by FrozenBeard** [comment]
Should be a simple variable. 
Bump.

**Comment by RoinujNosde** [comment]
I will look into it next Sunday.

**Comment by RoinujNosde** [comment]
@marcelo-mason what do you say about me turning this
```
allychat:
    tag-color: b
    name-color: f
    player-bracket:
        left: <
        right: '>'
    message-color: '3'
    tag-bracket:
        color: '8'
        left: '['
        right: ']'
    enable: true
```
into this
```
allychat:
    enable: true
    format: "&b[Ally Chat] &4%clan%.%nick-color%<%player%>: &b%message%"
    leader-color: '4'
    member-color: 'f'
```
?
Much easier to customize...
