### ISSUE TITLE
The chat update broke the Clanchat formatting, its showing as Ally chat formatting.

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#516]
My ally chat and crew chat are both using the same formatting from Ally chat after updating, They need to use their own separate formatting to tell the difference between the chats, This is now VERY confusing.
My formatting:

```
clanchat:
  enable: true
  tag-based-clan-chat: true
  announcement-color: e
  format: '%rank% &b%nick-color%%player% &7» &b%message%'
  rank: '&8[%rank%&8]'
  leader-color: l
  member-color: b
request:
  message-color: b
  ask-frequency-secs: 120
  max-asks-per-request: 600
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
allychat:
  enable: true
  format: '&8[&8%clan%&8] &7%nick-color%%player%&7 » &2%message%'
  rank: '&f[%rank%&f]'
  leader-color: o
  member-color: 7
```
This is what it looks like in game:
![2019-07-26_11 21 30](https://user-images.githubusercontent.com/144046/61945329-95d1fc00-af97-11e9-9773-1d6ef0da1c07.png)

What the crew chat should look like from my configs:
![Screenshot 2019-07-26 11 26 58](https://user-images.githubusercontent.com/144046/61945623-5e178400-af98-11e9-8311-3512a17ee974.png)
